import { createContext } from "react";

export const GlobalContext = createContext();

export const GlobalStorage = ({ children }) => {
  const dataProfile = {
    name: "𝗧𝗵𝗲𝗼𝗱𝗼𝗿𝘂𝘀",
    userVip: true,
    vipEnum: "PREMIUM",
    headImg:
      "https://s3.us-west-1.amazonaws.com/ai-character/uploaded/c/image/1727937488129_5dca518d.webp",
    avatar:
      "https://s3.us-west-1.amazonaws.com/ai-character/uploaded/c/image/1728009877102_159d9710.webp",
    bio: "❨ Discord: @ahirudo ❩",
  };
  const dataPublicBots = [
    {
      botId: "qpR8W",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "MY HERO ACADEMIA - HERO [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1727660161094_5bd9ce4b.webp",
      introduce: "✨ You are a new student at U.A. High School - MHA",
      botChats: "118.8k",
      botLikes: "54",
      botLikesInInt: 54,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "LEDPq",
      botType: 1,
      botCategory: 6,
      categoryName: "Games",
      characterName: "Demi-Human School [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1727545466079_0a77daaa.webp",
      introduce: "😶‍🌫️ Your first day at a school for Demi-Humans",
      botChats: "29.3k",
      botLikes: "19",
      botLikesInInt: 19,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "kgOo7",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "International College [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1727051709705_ff895a0e.webp",
      introduce: "🌍 You are in a international college",
      botChats: "19.2k",
      botLikes: "21",
      botLikesInInt: 21,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "aanjN",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Intrusion at Nazarick [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1727013063657_5f423ade.webp",
      introduce: "💀 Albedo, Shalltear, and Narberal have to handle you",
      botChats: "89.7k",
      botLikes: "51",
      botLikesInInt: 51,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "385PB",
      botType: 1,
      botCategory: 6,
      categoryName: "Games",
      characterName: "Tavern Tales [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1726928637308_59e56458.webp",
      introduce: "❤️ A lively haven nestled in the heart of town",
      botChats: "6.6k",
      botLikes: "18",
      botLikesInInt: 18,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "kgYeb",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Your Cold Marriage [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1726599230330_847a9dfd.webp",
      introduce: "Your cold, arranged marriage in a wealthy environment 🧊🩵",
      botChats: "448.5k",
      botLikes: "208",
      botLikesInInt: 208,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "MO2K4",
      botType: 1,
      botCategory: 6,
      categoryName: "Games",
      characterName: "Re/Life in Another World [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/src/avatar/gif_712bdccb03014d0a8db7b2b09771b9fc.webp",
      introduce: "You were born into another world.",
      botChats: "39.6k",
      botLikes: "39",
      botLikesInInt: 39,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "nZBed",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Transferred Student Hana [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1726321737265_b20bdc5d.webp",
      introduce: "A transfer student joins your college - Hana Yamamoto ✨",
      botChats: "31.0k",
      botLikes: "23",
      botLikesInInt: 23,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "kgpkV",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Straw Hats [RPG] - Marine Spy",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1726110000209_95504aa9.webp",
      introduce: "You have been sent on a spy mission on the Straw Hats.",
      botChats: "244.6k",
      botLikes: "543",
      botLikesInInt: 543,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "YRVKb",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Stepsister's Bullies",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725993689132_7a220398.webp",
      introduce: "Your stepsister is having problems with bullies",
      botChats: "380.6k",
      botLikes: "214",
      botLikesInInt: 214,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "wnAv3",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Emily Montague",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725859535174_b95a731c.webp",
      introduce: "You are the tutor to the final heir of the Montague lineage",
      botChats: "154.1k",
      botLikes: "89",
      botLikesInInt: 89,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "pxqKw",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Chunin Exam Chronicles",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725683398716_c61bda3a.webp",
      introduce: "The Hidden Leaf Village (Konohagakure) from the Naruto serie",
      botChats: "137.5k",
      botLikes: "77",
      botLikesInInt: 77,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "kgyob",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Feloria & Sylvia",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725592895050_eacea716.webp",
      introduce: "❲You've assembled a superb team for guild missions❳",
      botChats: "50.1k",
      botLikes: "50",
      botLikesInInt: 50,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "xgymZ",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Raven Nyx - ⟪ Arranged wife ⟫",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725459662142_f193414a.webp",
      introduce: "❲Arrangement in a cyberpunk dystopia❳",
      botChats: "25.6k",
      botLikes: "25",
      botLikesInInt: 25,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "rlJdO",
      botType: 1,
      botCategory: 2,
      categoryName: "Friends",
      characterName: "Trip in Europe",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725395252883_1cbd0a81.webp",
      introduce: "❲A holiday trip in Europe❳",
      botChats: "48.4k",
      botLikes: "29",
      botLikesInInt: 29,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "jgE4L",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Moira & Luana",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725385931215_d8f246f2.webp",
      introduce: "❲You found two playful females on the beach❳",
      botChats: "40.0k",
      botLikes: "31",
      botLikesInInt: 31,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "ZpE6A",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Hana & Kaede - ⌈ Kitsunes ⌋",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725230134706_3690753b.webp",
      introduce: "❲Two kitsunes running a magic shop with a human❳",
      botChats: "28.1k",
      botLikes: "18",
      botLikesInInt: 18,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "MOMVD",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Miriel & Lyria",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725123925946_ab6b2a3c.webp",
      introduce: "❲Two elf sisters met a strange human❳",
      botChats: "14.6k",
      botLikes: "19",
      botLikesInInt: 19,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "NwNjJ",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Molly",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725107038079_28e295c1.webp",
      introduce: "❲Your quiet and diligent classmate❳",
      botChats: "6.3k",
      botLikes: "6",
      botLikesInInt: 6,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "lpjol",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Dr. Victoria Sinclair",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725103793523_aa4a1698.webp",
      introduce: "❲Experiment-obsessed, no ethical boundaries in a secret lab❳",
      botChats: "29.3k",
      botLikes: "21",
      botLikesInInt: 21,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "B25yo",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "⌈ Cat girl ⌋ - Aiko",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725038498049_f6b7abed.webp",
      introduce: "❲An unconventional customer has arrived at your store❳",
      botChats: "29.9k",
      botLikes: "23",
      botLikesInInt: 23,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "RRVED",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Yumi",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724925325047_5b7b32c9.webp",
      introduce: "❲Shy with a gentle spirit that radiates kindness and grace❳",
      botChats: "17.3k",
      botLikes: "13",
      botLikesInInt: 13,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "RRV83",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Christine & Claire Nakamura",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1726010385889_c74e20bc.webp",
      introduce: "You caught your wife and mother hiding something from you",
      botChats: "13.5k",
      botLikes: "27",
      botLikesInInt: 27,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "6Dw47",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Kaori Ishikawa",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724849931212_f72ad8c2.webp",
      introduce: "❲ Your socially awkward classmate, quiet and introspective ❳",
      botChats: "25.9k",
      botLikes: "24",
      botLikesInInt: 24,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "Jr6md",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Velora Tenebris",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725894884342_772dd1f3.webp",
      introduce: "❲ Empress of Ebonspire, fallen angel turned demoness ❳",
      botChats: "25.3k",
      botLikes: "24",
      botLikesInInt: 24,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "jglVL",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Rina Kobayashi ⌈Possessive⌋",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1725846663227_02e4acf5.webp",
      introduce: "❲Your jealous best friend saw something shocking about you❳",
      botChats: "51.6k",
      botLikes: "47",
      botLikesInInt: 47,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "lpq4o",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "B-Rank Party - Dawnbringers",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724370217051_7be040fd.webp",
      introduce: "A B-rank party of fantasy heroes clashes a dragon",
      botChats: "5.8k",
      botLikes: "9",
      botLikesInInt: 9,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "nZAwO",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "⌈ Cousin ⌋ Chloe Rose",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724867487813_15402812.webp",
      introduce: "❲ Your shy cousin that is living at your home ❳",
      botChats: "16.6k",
      botLikes: "20",
      botLikesInInt: 20,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "PROlP",
      botType: 1,
      botCategory: 12,
      categoryName: "Anime",
      characterName: "Elf Sisters - Aeloria Forest",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724088857503_952e5906.webp",
      introduce: "Elven sisters found a human.",
      botChats: "28.6k",
      botLikes: "37",
      botLikesInInt: 37,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "PRODp",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "⌈ Maid ⌋ Lilith Nocturna",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1724869322453_43f52c42.webp",
      introduce: "❲ half-demonic maid with a cool detached demeanor ❳",
      botChats: "10.0k",
      botLikes: "16",
      botLikesInInt: 16,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "kgMDV",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "System of Prince Prodigy",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1723987342640_b2647abe.webp",
      introduce: "You are the legendary heir born to reshape the world",
      botChats: "12.6k",
      botLikes: "18",
      botLikesInInt: 18,
      isAddToHomePage: true,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "rY33p",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "The Popular Band [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1728210417725_6b2621ed.webp",
      introduce: "Your school's popular band invites you 🎤💟",
      botChats: "138",
      botLikes: "1",
      botLikesInInt: 1,
      isAddToHomePage: false,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
    {
      botId: "8p8kx",
      botType: 1,
      botCategory: 16,
      categoryName: "OC",
      characterName: "Your Maniac Classmate [VN]",
      avatar:
        "https://cdn.joyland.ai/ai-character/uploaded/c/image/1727910395875_26fef032.webp",
      introduce: "She locked you in the basement 🔒🎃",
      botChats: "1.1k",
      botLikes: "1",
      botLikesInInt: 1,
      isAddToHomePage: false,
      backgroundUrl: null,
      avatarBase: null,
      avatarBorder: null,
      storyName: null,
    },
  ];

  const sortedBots = [...dataPublicBots].sort((a, b) => {
    if (a.isAddToHomePage === b.isAddToHomePage) return 0;
    return !a.isAddToHomePage ? -1 : 1;
  });
  const sumLikes = () => {
    return sortedBots.reduce((total, bot) => {
      return total + (parseInt(bot.botLikesInInt) || 0); // Use botLikesInInt for the sum
    }, 0);
  };
  return (
    <GlobalContext.Provider
      value={{ dataProfile, dataPublicBots: sortedBots, sumLikes }}
    >
      {children}
    </GlobalContext.Provider>
  );
};

export default GlobalContext;
